Chore: Favicon change
Sivu-Tutorials/website pull request #7
Opened 2022-06-18 09:33 UTC by KarlGusta

Changes made:
- Changed the favicon to the new logo favicon.

2022-06-18 12:04 UTC, PatelN123 commented
Hey @KarlGusta,
Thanks for this. I think the Sivu light bulb icon would look best here instead of using the whole logo. Do you agree?

I also think it would be better to load the logo from the website rather than GitHub storage.

2022-06-18 16:14 UTC, PatelN123 requested changes

2022-06-18 16:14 UTC, PatelN123 commented on pages/_app.tsx
> +        <link rel='icon' type='image/png' sizes='96x96' href='https://user-images.githubusercontent.com/33565767/173816123-99707c2a-0bf0-46a0-a1c0-c4c4780beeb4.png' />
Can this be changed to a local path?
Also can we use just the lightbulb as the favicon here please.

2022-06-19 12:45 UTC, KarlGusta commented on pages/_app.tsx
> +        <link rel='icon' type='image/png' sizes='96x96' href='https://user-images.githubusercontent.com/33565767/173816123-99707c2a-0bf0-46a0-a1c0-c4c4780beeb4.png' />
Yes we can Patel. Thanks for your constructive feedback. I'll make the changes.

2022-06-20 10:05 UTC, PatelN123 commented
Sure, this works. It does look squished, but we can work on that later.

2022-06-20 10:05 UTC, merged